### ISSUE TITLE
Missing GIF ImageType

### ISSUE THREAD

**Issue by Tiffceet** [Zekfad/nhentai-api#10]
There are some doujins that uses .gif instead of .png / .jpg

This causes issue to getImageUrl(), it will return the wrong url because the image type is undefined

`const { API, } = require('nhentai-api');
const api = new API();
 
api.getBook(350866).then(book => {
    console.log(api.getImageURL(book.cover));    // https://t.nhentai.net/galleries/1864957/cover.undefined
    console.log(api.getImageURL(book.pages[1])); // https://i.nhentai.net/galleries/1864957/2.undefined
});`

Suggesting to add GIF ImageType

**Comment by Zekfad** [comment]
\>gif hentai doujin

![image](https://user-images.githubusercontent.com/8970959/110964782-9b46aa80-8364-11eb-954e-fb114ea7564e.png)

**Comment by Zekfad** [comment]
I've just added `dev` version artifacts to the [releases](https://github.com/Zekfad/nhentai-api/releases/tag/3.1.0-alpha-gif). So if you're ok with using `dev` version you install it (instructions provided).

**Comment by Zekfad** [comment]
Just published `dev` tag to npm.
You can now use `yarn add nhentai-api@dev`.

**Comment by Zekfad** [comment]
Also added `legacy` tag, with GIF support.
