### ISSUE TITLE
Error: Unable to verify first Certificate

### ISSUE THREAD

**Issue by Veilorth** [Zekfad/nhentai-api#17]
I have been following the basic examples located at the NPM README and I got this issue and I have no idea how to fix it.

```
(node:11232) UnhandledPromiseRejectionWarning: Error: unable to verify first certificate
```

Version I used: `3.0.2` / `latest`

**Comment by Zekfad** [comment]
Its either: your ISP blocking the connection or you're missing some CA's.
You can try to use this package: _[node_extra_ca_certs_mozilla_bundle](https://www.npmjs.com/package/node_extra_ca_certs_mozilla_bundle)_.
Also you can look for answers and solutions [here on _SA_](https://stackoverflow.com/a/32440021/8035872).

**Comment by Veilorth** [comment]
I followed your instructions above and it doesn't seem to work; it still gives me the same error.

**Comment by Zekfad** [comment]
What is your specs? In particular what is your OS, Node version, Last time you updated the system?
Do you have access to nhentai from the browser?

**Comment by Veilorth** [comment]
> What is your specs? In particular what is your OS, Node version, Last time you updated the system?
> Do you have access to nhentai from the browser?

I'm on Windows 10 and my current Node version is `14.16.0` and since I'm using Opera GX as my browser, I use VPN to access the site.

**Comment by Veilorth** [comment]
> > What is your specs? In particular what is your OS, Node version, Last time you updated the system?
> > Do you have access to nhentai from the browser?
> 
> I'm on Windows 10 and my current Node version is `14.16.0` and since I'm using Opera GX as my browser, I use VPN to access the site.

Ahh never mind, I fixed them already! Thanks for the help 👍

**Comment by Zekfad** [comment]
Could you tell what was the cause, in case anyone else will have the same issue?

**Comment by Veilorth** [comment]
Yes, sorry for the late reply (I did not check my GitHub:sweat_smile:)

As you said earlier, it could be either you missing some CA's or the site was blocked (it doesn't allow you any access to the site). I simply fix this by using VPN.
