### ISSUE TITLE
When searching for touhou, it crashes

### ISSUE THREAD

**Issue by jdbuenol** [Zekfad/nhentai-api#21]
[output](https://github.com/jdbuenol/touhou-search/blob/main/output.txt)

As the title says when using "touhou" as parameter for the api.search() method the app crashes.

My code:

"doujins.search('touhou').then(search => {
	search.getNextPage().then(search2 => {
    console.log(search2.books[0]);
  })
}).catch(err => console.log(err))"

This doesn't happen when using other arguments like "fate" or "pokemon".

**Comment by Zekfad** [comment]
This is the same as #19
For some reason API returns 404, no fix available.
But here's workaround: try refining search, e.g. use combinations with language, number of pages, or something else.
For me it was working with `uploaded:>3d`.
