### ISSUE TITLE
APIError: Request failed with status code 503

### ISSUE THREAD

**Issue by NewblyAaron** [Zekfad/nhentai-api#24]
Hello! Sorry if this seems to be a noob question. I'm new with JS and this would be the first time I'm posting an issue in GitHub. 

I'm using this API in a discord bot I'm making for myself. It was working last three days ago, but today it seems to always say this: 
`APIError: Request failed with status code 503` [Full log is here.](https://github.com/Zekfad/nhentai-api/files/8191606/logs.txt)

It started once I deployed it on Heroku. I tried also running it locally here on my laptop but it also shows the same error. I don't see anything wrong with how I coded it... am I missing something here? I'm also able to access the site fine, so I don't think this would be an ISP issue on my end.
[Here is a part of my code using the API.](https://github.com/Zekfad/nhentai-api/files/8191615/sauce.txt)

Thank you in advance.

**Comment by cerinoligutom** [comment]
Experiencing this as well. For our use case, we only use this lib to get a specific book. From what I've traced on the [relevant code of this lib](https://github.com/Zekfad/nhentai-api/blob/64cde9538f7d4f6e80c5b10cba92a0f8e0898e05/src/api.js#L359), the full endpoint to get a book for let's say `177013`, would be a GET request to `https://nhentai.net/api/gallery/book/177013`. But hitting that endpoint manually just returns a 404, seeing that the response error code is also 503, should have something to do on the API side.

Could it be related to this https://github.com/Dar9586/NClientV2/issues/402#issuecomment-1059901767? Or did the endpoint change 🤔

**Comment by underscore-en** [comment]
I believe its a problem on their side. I have been experiencing 503s earlier.

As of now, the endpoints returns 200.

**Comment by NewblyAaron** [comment]
Looks like it's fixed now. It was indeed a problem on the site itself. It's working properly now. Thanks for the information and help!
