### ISSUE TITLE
Most recent Upload

### ISSUE THREAD

**Issue by SauceDude** [Zekfad/nhentai-api#7]
How do we get the most recent upload to the site?

**Comment by Zekfad** [comment]
They allow to search for everything. By default sort method is recent, so you just have to search for `*`, e.g.:
```js
api.search('*').then(search => {
//...
});
```

**Comment by Zekfad** [comment]
I guess my answer is suitable, if there are additional problems, you can comment here and I'll reopen issue.

**Comment by Zekfad** [comment]
API seems to reject this method now.
I'll have to find a fix or workaround.

**Comment by Zekfad** [comment]
Old solution seems to works as for now. :D
